spring:
  application:
    name: "consumer app"
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost}:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
#      listener:
##         immediate-stop: true
##        ack-mode: RECORD
#        async-acks: true

logging:
  pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%18.18t]){yellow} %clr(:){red} %clr(%m){faint}%n"
  level:
    org.springframework.kafka: debug
